### ISSUE TITLE
Terminal Commands with Suffixes do not show the suffix in --help

### ISSUE THREAD

**Issue by jeffderek** [ProfessorAire/Evands.Pellucid-Crestron#53] opened 2021-07-20 00:25 UTC
When a terminal command is created with a suffix, the base command is what is shown in the --help screen.

![image](https://user-images.githubusercontent.com/3788655/126243935-b4c1ce10-359e-48b3-84db-76e3b09c0a91.png)

As you can see in the screenshot, the command `app -h` shows two display commands, each with the alias dis.  No distinction between the two is shown.  `app dis -h` should work, according to the help commands, but it doesn't.  You have to actually use the suffixes as declared for it to work.

**Comment by ProfessorAire** [comment] 2021-07-20 01:56
Duplicate of #48

**Comment by jeffderek** [comment] 2021-07-20 03:44
doh!  My bad

**Comment by ProfessorAire** [comment] 2021-07-28 04:15
Resolved with #48.

**Closed by ProfessorAire** 2021-07-28 04:15 UTC
Labels: bug, duplicate
